# Generated by Django 4.0.7 on 2022-09-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('birdsong', '0006_auto_20220428_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
